src/actions/index.js, src/components/Homepage.css, src/components/Homepage.js, src/components/ReduxHomepage.js, src/components/ResultsTable.css, src/index.css, src/reducers/resources.js
Closes #16 
User can toggle between grid and list view for homepage resources.
(Note: will not return any resources until PR #20 is merged since anonymous auth is turned off on the FHIR server)
=> 💄Adding list view toggle to homepage

src/components/Homepage.css, src/components/Homepage.js, src/components/OntologyHomepage.js, src/components/SortableTable.css, src/components/SortableTable.js
A sortable table was being used by multiple components, so it's been moved out into its own reusable component.
=> ♻️Sortable table component

README.md, package-lock.json, src/reducers/resources.js, src/utils/api.js
All requests have Basic Auth in the headers.
=> Add auth headers to requests

src/components/App.css, src/components/App.js
Closes #28 
Clicking on the banner now leads the user to the homepage.
=> 💄Added link to homepage

src/components/tables/ReferenceTable.js, src/components/tables/ResultsTable.js, src/utils/api.js
Closes #36 
Additional reference table to show the references in the payload of the given ID.
=> ✨References include resources referenced by the given ID

src/components/DataBarChart.js, src/components/ResourceDetails.css, src/components/ResourceDetails.js, src/components/tables/ResultsTable.js
Charts and tables can show extensions on the resource details page.
Also, if an attribute has more than 15 options, it will display in a bar chart.
=> ✨Charts show extensions

src/components/OntologyHomepage.js
Closes #25 
Spinner was absent when user selected new FHIR API.
=> 🐛Adding spinner to Ontology page

src/components/DataBarChart.js, src/components/DataPieChart.js, src/components/ResourceDetails.css, src/components/ResourceDetails.js
Closes #38 
For example, clicking on the "Female" pie sector for Individuals displays a table of all Individuals where gender = female, and clicking on the "Whole blood" bar in the Biosample bar chart displays a table of all Biosamples where type = Whole blood
=> ✨Clicking on a chart sector shows table of resources where attribute = selected value

src/components/OntologyHomepage.js, src/components/ReduxOntologyHomepage.js
Closes #42 
Clicking on a row in the ontology page table opens a modal show the payload for that resource.
=> ✨Clicking on CodeSystem shows payload

package-lock.json, package.json
Closes #45 
Package.json contained old app name.
=> ♻️Updating app name in package.json

src/components/DataBarChart.js, src/components/ResourceDetails.css
Closes #39 
Bar charts only show values with data.
=> 🐛Removed values with no data from bar charts

package-lock.json, package.json, src/components/tables/ReferenceTable.js, src/components/tables/ResultsTable.js
Closes #48 
Includes syntax highlighting and collapsible sections.
=> 💄JSON payloads are formatted on details view

src/components/OntologyHomepage.js
Format the JSON for ontology detail payloads to have syntax highlighting and collapsible sections.
=> Format ontology JSON

src/components/Homepage.js, src/components/OntologyHomepage.js, src/components/ReduxHomepage.js, src/components/ReduxOntologyHomepage.js, src/components/ReduxResourceDetails.js, src/components/ResourceDetails.js, src/components/tables/ReferenceTable.js, src/components/tables/ResultsTable.js, src/reducers/ontologies.js, src/utils/api.js, src/utils/common.js
Closes #26 
Closes #42 
Error handling occurs throughout app, user can navigate away from a page and requests will be canceled with no memory leaks.
=> 🥅Error handling

README.md, src/.env.example, src/actions/index.js, src/components/App.css, src/components/App.js, src/components/Login.css, src/components/Login.js, src/components/ReduxApp.js, src/components/ReduxServerConfiguration.js, src/components/ResourceDetails.js, src/components/ServerConfiguration.css, src/components/ServerConfiguration.js, src/components/tables/ResultsTable.js, src/config.js, src/reducers/index.js, src/reducers/ontologies.js, src/reducers/resources.js, src/reducers/user.js, src/utils/api.js, src/utils/common.js
Closes #24 
Closes #56 
User can view server options, edit, and add.
Note: for a production ready system (aka non-prototype) probably would be better to store server options in a DB instead of the Redux store - the Redux store only persists for a browser session.
=> ✨Configuration UI for adding/updating a server

README.md, src/.env.example, src/actions/index.js, src/components/App.js, src/components/Login.css, src/components/ReduxApp.js, src/components/ReduxHomepage.js, src/components/ReduxLogin.js, src/components/ReduxOntologyHomepage.js, src/components/ReduxResourceDetails.js, src/components/ReduxServerConfiguration.js, src/components/ServerConfiguration.css, src/components/ServerConfiguration.js, src/config.js, src/reducers/app.js, src/reducers/index.js, src/reducers/resources.js, src/utils/api.js, src/utils/common.js
Closes #57 
General refactor of reducers and server configuration  to make the app more extensible to other auth types in the future, and to make code more readable.
Leaving out OAuth for now.
=> ♻️Refactoring reducers and server configuration

.circleci/config.yml, .dockerignore, .gitignore, Dockerfile, README.md, bin/nginx.conf, docker-compose.yml
=> 🐳 Dockerize the app

src/components/tables/SortableTable.js
Closes #67 
Fixes bug of table not updating on new search result
=> 🐛Adding statement to update table when props change

cypress/integration/servers.js
Tests for the server and login UI.
=> ✅ Add server tests

cypress/fixtures/attributeDetails/allPatients.json, cypress/fixtures/attributeDetails/patientSnapshot.json, cypress/integration/attributeDetails.js, src/components/AttributeDetails.js
Adding tests for the attribute details page.
=> ✅ Add attribute details page tests

.gitignore, Dockerfile, Jenkinsfile, bin/env.sh, bin/nginx.conf, bin/start_up.sh, package.json, public/index.html, src/config.js, src/utils/common.js
=> 👷 Deploy dashboard to production

.github/workflows/gh_release.yml
=> 👷 Add GH release workflow

cypress/fixtures/resourceIdDetails/capabilityStatementReferences.json, cypress/fixtures/resourceIdDetails/conditionDetails.json, cypress/fixtures/resourceIdDetails/patientDetails.json, cypress/fixtures/resourceIdDetails/patientResourceDetails.json, cypress/fixtures/resourceIdDetails/patientStructureDefinition.json, cypress/fixtures/resourceIdDetails/resourceDetails.json, cypress/integration/patientIdDetails.js, cypress/integration/resourceIdDetails.js, src/.env.example, src/components/DataScatterChart.css, src/components/DataScatterChart.js, src/components/IdDetails.js, src/components/tables/ReferenceTable.js, src/components/tables/Timeline.js, src/config.js
Adds a "timeline" tab in place of "references" for any resources with a base type of Patient.
=> ✨Add Timeline to Patient resource

package-lock.json, package.json, src/components/DataScatterChart.js, src/components/IdDetails.css, src/components/IdDetails.js, src/components/SubmitPatientData.js, src/components/tables/Timeline.js, src/utils/api.js
Adding tab to Patient resource to submit additional data.
=> ✨ Submit Patient data feature

src/components/Header.css, src/components/Header.js
ID details page was inheriting the background color of the header - added an additional class to the header to restrict its styles to the header to stop other classes from inheriting.
=> 💄 Additional class to header

src/components/AttributeDetails.css, src/components/AttributeDetails.js, src/components/ReduxAttributeDetails.js
It is interesting to see which Patients have certain Conditions, Observations, etc. so when looking up a condition of interest (for example), a tab will be present to show which Patients are associated with that condition.
=> ✨ Add Patient tab to attributes details page

src/components/tables/ReferenceTable.js
Closes #93 
References table will include links in addition to references.
=> ♻️ Adding in links to reference table

.circleci/config.yml, docker-compose.yml
=> 🐛 Add missing env vars to Docker Compose

cypress/integration/servers.js, src/config.js
=> ♻️ Updating old default urls to be the KF dev and QA urls

CHANGELOG.md
- Emojis: ♻️ x1, 🐛 x2
- Categories: Other Changes x1, Fixes x2
- [#109](https://github.com/kids-first/kf-ui-fhir-data-dashboard/pull/109) - ♻️ Updating old default urls to be the KF dev and QA urls - [2c31931a](https://github.com/kids-first/kf-ui-fhir-cohort-builder/commit/2c31931a916197901d26c088aceff50ab0547413) by [abgeorge7](https://github.com/abgeorge7)
- [#108](https://github.com/kids-first/kf-ui-fhir-data-dashboard/pull/108) - 🐛 Remove Auth headers from request if auth is not needed - [02665f1b](https://github.com/kids-first/kf-ui-fhir-cohort-builder/commit/02665f1b7140c9a2fb2d55df432a0bdd740fdb42) by [abgeorge7](https://github.com/abgeorge7)
- [#107](https://github.com/kids-first/kf-ui-fhir-data-dashboard/pull/107) - 🐛 Add missing env vars to Docker Compose - …
=> 🏷 Release 0.3.0

README.md
=> 💡Updating README to include KF urls
